name: vae
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  - typer
  - scikit-learn
  - pytorch
  - pytorch-cuda=12.1 # with gpu
  - torchvision
  - torchaudio
